# Generated by Django 2.2 on 2019-05-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Введите название задачи', max_length=20, unique=True),
        ),
    ]
