# Generated by Django 2.2 on 2019-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='quality',
            field=models.CharField(choices=[('+', 'Завысил'), ('-', 'Занизил'), ('=', 'Не пошла на третью проверку')], default='=', max_length=1),
            preserve_default=False,
        ),
    ]
