# Generated by Django 2.2 on 2019-04-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите образование', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['year_of_birth']},
        ),
        migrations.AddField(
            model_name='profile',
            name='job_if_education',
            field=models.CharField(help_text='Введите образовательное учреждение', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_if_not_education',
            field=models.CharField(help_text='Введите место работы', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(help_text='Введите отчество', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Education'),
        ),
    ]
