# Generated by Django 2.2 on 2019-04-28 13:35

from django.db import migrations, models
import django.db.models.deletion
import profiles.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190428_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите образование', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите образование', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(help_text='Введите квалификацию(по диплому)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=profiles.customfields.IntegerRangeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.AcademicDegree'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Post'),
        ),
    ]
