# Generated by Django 2.2 on 2019-05-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190501_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['leader__username'], 'permissions': (('can_export_group', 'Can export group'),)},
        ),
    ]
